name: Check quality
on:
  push:

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis number shapes
        working-directory: ./homework-3-number-shapes
        run: flutter analyze
      - name: Run analysis guess number
        working-directory: ./homework-2-guess-number
        run: flutter analyze
      - name: Run analysis currency converter
        working-directory: ./homework-1-currency-converter
        run: flutter analyze
      - name: Run analysis basic phrases
        working-directory: ./homework-4-basic-phrases
        run: flutter analyze
       - name: Run analysis x & 0
        working-directory: ./homework_5_x_0
        run: flutter analyze
